export const ANALYTICS_EVENTS = {
	CHARACTER_CREATE: "character_create",
	CHARACTER_UPDATE: "character_update",
	CHARACTER_DELETE: "character_delete",
	MONSTERLING_CREATE: "monsterling_create",
	MONSTERLING_UPDATE: "monsterling_update",
	MONSTERLING_DELETE: "monsterling_delete",
	LOADOUT_CREATE: "loadout_create",
	LOADOUT_UPDATE: "loadout_update",
	LOADOUT_DUPLICATE: "loadout_duplicate",
	LOADOUT_DELETE: "loadout_delete",
	LOADOUT_PREVIEW: "loadout_preview",
	CODEX_MARK_COMPLETE: "codex_mark_complete",
	CODEX_MARK_INCOMPLETE: "codex_mark_incomplete",
	CODEX_ADD_FAVORITE: "codex_add_favorite",
	CODEX_REMOVE_FAVORITE: "codex_remove_favorite",
	CODEX_RESET: "codex_reset",
	CHARACTERS_RESET: "characters_reset",
	MONSTERLINGS_RESET: "monsterlings_reset",
	LOADOUTS_RESET: "loadouts_reset",
	LOADOUT_COPY_ATTEMPT: "loadout_copy_attempt",
	LOADOUT_COPY_SUCCESS: "loadout_copy_success",
	LOADOUT_COPY_FAILURE: "loadout_copy_failure",
	LOADOUT_DOWNLOAD_ATTEMPT: "loadout_download_attempt",
	LOADOUT_DOWNLOAD_SUCCESS: "loadout_download_success",
	LOADOUT_DOWNLOAD_FAILURE: "loadout_download_failure",
	GOOGLE_DRIVE_LOGIN_ATTEMPT: "google_drive_login_attempt",
	GOOGLE_DRIVE_LOGIN_SUCCESS: "google_drive_login_success",
	GOOGLE_DRIVE_LOGIN_FAILURE: "google_drive_login_failure",
	GOOGLE_DRIVE_LOGOUT_ATTEMPT: "google_drive_logout_attempt",
	GOOGLE_DRIVE_LOGOUT_SUCCESS: "google_drive_logout_success",
	GOOGLE_DRIVE_LOGOUT_FAILURE: "google_drive_logout_failure",
	SYNC_CONFLICT_KEEP_LOCAL_ATTEMPT: "sync_conflict_keep_local_attempt",
	SYNC_CONFLICT_KEEP_LOCAL_SUCCESS: "sync_conflict_keep_local_success",
	SYNC_CONFLICT_KEEP_LOCAL_FAILURE: "sync_conflict_keep_local_failure",
	SYNC_CONFLICT_KEEP_REMOTE_ATTEMPT: "sync_conflict_keep_remote_attempt",
	SYNC_CONFLICT_KEEP_REMOTE_SUCCESS: "sync_conflict_keep_remote_success",
	SYNC_CONFLICT_KEEP_REMOTE_FAILURE: "sync_conflict_keep_remote_failure",
} as const;

export type AnalyticsEventName =
	(typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];
