import {
	MONSTERLING_CARD_WIDTH,
	MONSTERLING_COMPACT_CARD_WIDTH,
} from "@/components/monsterlings/components/monsterling-constants";

export const LOADOUT_PREVIEW_PORTRAIT_SIZE = 120;
export const LOADOUT_PREVIEW_CHARACTER_SLOT_WIDTH = 268;
export const LOADOUT_PREVIEW_GAP = 12;
export const LOADOUT_PREVIEW_SURFACE_PADDING = 24;

export const LOADOUT_PREVIEW_COMPACT_WIDTH =
	LOADOUT_PREVIEW_CHARACTER_SLOT_WIDTH +
	4 * MONSTERLING_COMPACT_CARD_WIDTH +
	4 * LOADOUT_PREVIEW_GAP +
	LOADOUT_PREVIEW_SURFACE_PADDING;

export const LOADOUT_PREVIEW_DETAILED_WIDTH =
	LOADOUT_PREVIEW_CHARACTER_SLOT_WIDTH +
	4 * MONSTERLING_CARD_WIDTH +
	4 * LOADOUT_PREVIEW_GAP +
	LOADOUT_PREVIEW_SURFACE_PADDING;

export const LOADOUT_PREVIEW_COMPACT_HIDDEN_EQUIPMENT_WIDTH =
	LOADOUT_PREVIEW_COMPACT_WIDTH +
	LOADOUT_PREVIEW_PORTRAIT_SIZE +
	LOADOUT_PREVIEW_GAP;

export const LOADOUT_PREVIEW_DETAILED_HIDDEN_EQUIPMENT_WIDTH =
	LOADOUT_PREVIEW_DETAILED_WIDTH +
	LOADOUT_PREVIEW_PORTRAIT_SIZE +
	LOADOUT_PREVIEW_GAP;
