/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthGoogleSessionRouteImport } from './routes/api/auth/google-session'
import { Route as ApiAuthGoogleLogoutRouteImport } from './routes/api/auth/google-logout'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'

const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleSessionRoute = ApiAuthGoogleSessionRouteImport.update({
  id: '/api/auth/google-session',
  path: '/api/auth/google-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleLogoutRoute = ApiAuthGoogleLogoutRouteImport.update({
  id: '/api/auth/google-logout',
  path: '/api/auth/google-logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/callback': typeof CallbackRoute
  '/issues': typeof IssuesRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/google-logout': typeof ApiAuthGoogleLogoutRoute
  '/api/auth/google-session': typeof ApiAuthGoogleSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/callback': typeof CallbackRoute
  '/issues': typeof IssuesRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/google-logout': typeof ApiAuthGoogleLogoutRoute
  '/api/auth/google-session': typeof ApiAuthGoogleSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/callback': typeof CallbackRoute
  '/issues': typeof IssuesRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/google-logout': typeof ApiAuthGoogleLogoutRoute
  '/api/auth/google-session': typeof ApiAuthGoogleSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/callback'
    | '/issues'
    | '/api/auth/google'
    | '/api/auth/google-logout'
    | '/api/auth/google-session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/callback'
    | '/issues'
    | '/api/auth/google'
    | '/api/auth/google-logout'
    | '/api/auth/google-session'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/callback'
    | '/issues'
    | '/api/auth/google'
    | '/api/auth/google-logout'
    | '/api/auth/google-session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CallbackRoute: typeof CallbackRoute
  IssuesRoute: typeof IssuesRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthGoogleLogoutRoute: typeof ApiAuthGoogleLogoutRoute
  ApiAuthGoogleSessionRoute: typeof ApiAuthGoogleSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google-session': {
      id: '/api/auth/google-session'
      path: '/api/auth/google-session'
      fullPath: '/api/auth/google-session'
      preLoaderRoute: typeof ApiAuthGoogleSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google-logout': {
      id: '/api/auth/google-logout'
      path: '/api/auth/google-logout'
      fullPath: '/api/auth/google-logout'
      preLoaderRoute: typeof ApiAuthGoogleLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CallbackRoute: CallbackRoute,
  IssuesRoute: IssuesRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthGoogleLogoutRoute: ApiAuthGoogleLogoutRoute,
  ApiAuthGoogleSessionRoute: ApiAuthGoogleSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
